### ISSUE TITLE
second page:Uncaught (in promise) ReferenceError: useRouter is not defined 

### ISSUE THREAD

**Issue by huoguo32** [byoungd/modern-vue-template#2]
![image](https://user-images.githubusercontent.com/99411543/184790268-45e472fe-920f-4bc4-82e9-a00f0419b4c9.png)

**Comment by huoguo32** [comment]
请问为什么会出现这种错误，该怎么解决呢？

**Comment by byoungd** [comment]
> 请问为什么会出现这种错误，该怎么解决呢？

原因：非常抱歉，这是因为本项目并未开启Api自动导入的特性而我忘了在这个页面进行测试

解决方法：需要把 `useRouter watchEffect useI18n` import一下 ，该问题已经修复，请拉取最新的代码。
